### ISSUE TITLE
Incompatible with puppet 4

### ISSUE THREAD

**Issue by mzhaase** [fraenki/puppet-sshkeys#10]
users get not created with puppet 4 agent.

**Comment by artem-sidorenko** [comment]
@mzhaase yes, I know its not compatible with puppet 4 yet.
When I have more time I will make it puppet 4 compatible (PRs are welcome), as I don't use puppet anymore it will take some time.

**Comment by mzhaase** [comment]
Do you have an idea what causes it?

**Comment by artem-sidorenko** [comment]
@mzhaase I guess some changes because of Hiera conversion to puppet 4 API

**Comment by mzhaase** [comment]
I noticed that switching from hiera_hash to just hiera makes it work again.

**Comment by artem-sidorenko** [comment]
@mzhaase thx, I'll check this when I have time. If you can fix it and can extend the tests to puppet 4, feel free to provide a PR

**Comment by mzhaase** [comment]
Hi,
I don't know if this helps you or if it was just me being an idiot, but per default in puppet, the puppet folder and all files in it are owned by root. however all hiera files have to be owned by puppet.

**Comment by artem-sidorenko** [comment]
@mzhaase as I stopped using puppet about 2 years ago, I'm not going to maintain this module anymore. Sorry for any inconvenience caused

**Comment by fraenki** [comment]
@mzhaase: Is this still an issue for you? What does your hiera data look like?

**Comment by mzhaase** [comment]
Turned out it was a permission problem, as the default permissions are different under puppet 4.
